### ISSUE TITLE
Error: QXcbConnection: Could not connect to display :0

### ISSUE THREAD

**Issue by malikolivier** [pmiklos/docker-solarcoin-qt#1]
The wallet was working for a moment.

![Wallet is running](https://user-images.githubusercontent.com/14120117/39159661-b6fded6c-47a1-11e8-80d3-4c4dd4450efd.png)

However sometimes it does not run, I get an error as below:

```
$ ./solarcoin-qt.sh 
QXcbConnection: Could not connect to display :0
```

(Running Ubuntu 17.10 with i3 and x11)

I will see if I can debug it. Any idea?

**Comment by pmiklos** [comment]
It must be something to do with the generated xauth file. I wasn't able to reproduce it so far. I am not an expert in the xauth area, but if you can provide some additional info eg. the contents and permissions of `/tmp/.docker.xauth` when you get that error, I could do some research. As a workaround running something like `xhost +` before you start solarcoin-qt.sh might help.

**Comment by malikolivier** [comment]
Hmmm. I was not able to reproduce it. Now it works without issue (I did not change anything on my system). I will reopen and provide additional info if it occurs again.
